# Generated by Django 3.1.6 on 2021-02-17 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helfffencore', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='contact',
            field=models.TextField(default='-'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='number_of_helpers_needed',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
