repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: end-of-file-fixer
      - id: check-json
      - id: check-added-large-files
      - id: check-yaml
      - id: check-merge-conflict
      - id: check-docstring-first
      - id: debug-statements
  - repo: https://github.com/PyCQA/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        args: [ "--config=src/.flake8" ]
        additional_dependencies:
          - flake8-print
          - flake8-builtins
          # - flake8-annotations
          - flake8-commas
          - flake8-isort
          - flake8-json
          - flake8-debugger
          - flake8-bugbear
          - flake8-docstrings
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.3.1
    hooks:
      - id: pyupgrade
        args: [ "--py311-plus" ]
  - repo: https://github.com/asottile/add-trailing-comma
    rev: v2.4.0
    hooks:
      - id: add-trailing-comma
        args: [ "--py36-plus" ]
  - repo: https://github.com/Lucas-C/pre-commit-hooks-safety
    rev: v1.3.1
    hooks:
      - id: python-safety-dependencies-check
  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.4
    hooks:
      - id: bandit
        args: [ "--ini", ".bandit" ]
  - repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
    rev: v9.4.0
    hooks:
      - id: commitlint
        stages: [ "commit-msg" ]
        additional_dependencies:
          - "@commitlint/config-conventional"
default_stages:
  - commit
default_install_hook_types:
  - pre-commit
  - commit-msg
