# Generated by Django 3.1.6 on 2021-02-17 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helfffencore', '0004_task_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='helpoffer',
            name='additional_information',
            field=models.TextField(default='-'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='helpoffer',
            name='contact',
            field=models.TextField(default='-'),
            preserve_default=False,
        ),
    ]
