FROM docker.io/python:3.13


# Install system dependencies
RUN apt-get update && \
    apt-get upgrade -y && \
    apt-get install -y tini && \
    rm -rf /var/lib/apt/lists/*


# Setup pipx to be accessible by all users
ENV PIPX_HOME=/app/.local/pipx \
    PIPX_BIN_DIR=/app/.local/bin \
    PATH=/app/.local/bin:$PATH

# Install pipx and poetry
RUN python3 -m pip install pipx
RUN pipx install poetry

# Setup poetry to use /app/src/.venv as path
RUN poetry config virtualenvs.in-project true

# Set WORKDIR
WORKDIR /app/src

ENTRYPOINT ["poetry", "run"]
CMD python manage.py runserver 0.0.0.0:8000

# Mark port 8000 as exposed
EXPOSE 8000
